##############################################
##          CONFIGURACION GENERAL           ##
##############################################

spring.application.name=Instituto

application.title=${APPLICATION_TITLE:Institutos API Rest Spring Boot}
application.version=${APPLICATION_VERSION:1.0.0}

server.port=${PORT:3001}
server.tomcat.redirect-context-root=false

api.version=${API_VERSION:v1}
server.error.include-message=always


##############################################
##                 LOGGING                  ##
##############################################

# Tu paquete en debug
logging.level.es.juanito.institutos=DEBUG

# Hibernate: ver SQL pero sin spam
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=OFF

# Spring MVC normal
logging.level.org.springframework.web=INFO
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=OFF


##############################################
##      CONFIGURACION BASE DE DATOS H2      ##
##############################################

spring.sql.init.mode=always
spring.datasource.url=jdbc:h2:mem:institutosapirest
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true


##############################################
##             HIBERNATE & JPA              ##
##############################################

spring.jpa.open-in-view=false


##############################################
##                 I18N                     ##
##############################################

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false


##############################################
##                 SWAGGER                  ##
##############################################

springdoc.swagger-ui.enabled=true


##############################################
##                 GRAPHQL                  ##
##############################################

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.http.path=/graphql


##############################################
##            PEBBLE Template Engine        ##
##############################################

pebble.suffix=.peb.html
pebble.cache=false
spring.pebble.charset=UTF-8


##############################################
##                  JWT                     ##
##############################################

jwt.secret.key=Q0xAVkUuU0VDUkVUQS5TWVBFUi5TWUlTVEVBLkRFIlBFUkZJQ0lFWg==
jwt.expiration.time=3600000
jwt.refresh-token.expiration=604800000


##############################################
##             CONFIGURACION CACHE          ##
##############################################

spring.cache.ehcache.config=classpath:ehcache.xml


##############################################
##             CONFIGURACION DEVTOOLS       ##
##############################################

spring.devtools.restart.enabled=false
spring.devtools.restart.additional-paths=src/main/java,src/main/resources
spring.devtools.restart.exclude=static/**,public/**
spring.devtools.livereload.enabled=true
spring.devtools.livereload.port=35729
spring.mvc.trailing-slash=false
