##############################################
##          CONFIGURACION GENERAL           ##
##############################################

spring.application.name=Instituto

# Puerto de la aplicaci\u00F3n (lee variable de entorno PORT, si no existe usa 3000)
server.port=${PORT:3000}

# Version de la API
api.version=${API_VERSION:v1}

# Incluir mensajes en las excepciones
server.error.include-message=always

# Logging nivel DEBUG para tu paquete
logging.level.es.juanito.institutos=DEBUG

##############################################
##      CONFIGURACION BASE DE DATOS H2      ##
##############################################

# Base de datos en memoria H2
spring.sql.init.mode=never
spring.datasource.url=jdbc:h2:mem:institutosapirest
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create-drop

##############################################
##             HIBERNATE & JPA              ##
##############################################

# Evita Open Session in View
spring.jpa.open-in-view=false

# Logging de par\u00E1metros en las consultas
logging.level.org.hibernate.orm.jdbc.bind=TRACE

##############################################
##           CONFIGURACION JWT              ##
##############################################

# Clave secreta JWT (debe coincidir con @Value en tu servicio)
jwt.secret.key=Q0xAVkUuU0VDUkVUQS5TWVBFUi5TWUlTVEVBLkRFIlBFUkZJQ0lFWg==

# Tiempo de expiraci\u00F3n del Token (milisegundos)
jwt.expiration.time=3600000

# Tiempo de expiraci\u00F3n del Refresh Token (milisegundos)
jwt.refresh-token.expiration=604800000

##############################################
##             CONFIGURACION CACHE          ##
##############################################

# Ehcache
spring.cache.ehcache.config=classpath:ehcache.xml
