##############################################
##          CONFIGURACION GENERAL           ##
##############################################

spring.application.name=Instituto

# Datos de app (para banner/footer/pebble)
application.title=${APPLICATION_TITLE:Institutos API Rest Spring Boot}
application.version=${APPLICATION_VERSION:1.0.0}

# Puerto (si no existe PORT usa 3000)
server.port=${PORT:3000}
server.tomcat.redirect-context-root=false


# Versionado API
api.version=${API_VERSION:v1}

# Mostrar mensaje en errores (para excepciones)
server.error.include-message=always


##############################################
##                 LOGGING                  ##
##############################################

# Nivel DEBUG solo para tu paquete
logging.level.es.juanito.institutos=DEBUG

# Para ver los valores de los par\u00E1metros consultas Hibernate 6 / Spring Boot 3
logging.level.org.hibernate.orm.jdbc.bind=TRACE

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE



##############################################
##      CONFIGURACION BASE DE DATOS H2      ##
##############################################

# Base de datos en memoria H2
spring.sql.init.mode=always
spring.datasource.url=jdbc:h2:mem:institutosapirest
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update




##############################################
##             HIBERNATE & JPA              ##
##############################################

# Evita Open Session in View
spring.jpa.open-in-view=false


##############################################
##             I18N              ##
##############################################

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false


##############################################
##                 SWAGGER                  ##
##############################################

# Habilitar swagger (quitar en producci\u00F3n)
springdoc.swagger-ui.enabled=true


##############################################
##                 GRAPHQL                  ##
##############################################

# Habilitar GraphiQL (playground web)
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

# Endpoint GraphQL
spring.graphql.http.path=/graphql


##############################################
##            PEBBLE Template Engine        ##
##############################################

pebble.suffix=.peb.html
pebble.cache=false
spring.pebble.charset=UTF-8


##############################################
##                  JWT                     ##
##############################################

# Usa los mismos nombres que tengas en tu c\u00F3digo con @Value
jwt.secret.key=Q0xAVkUuU0VDUkVUQS5TWVBFUi5TWUlTVEVBLkRFIlBFUkZJQ0lFWg==

# Expiraci\u00F3n del Token (ms) 1 hora
jwt.expiration.time=3600000

# Expiraci\u00F3n Refresh Token (ms) 7 d\u00EDas
jwt.refresh-token.expiration=604800000


##############################################
##             CONFIGURACION CACHE          ##
##############################################

# Ehcache
spring.cache.ehcache.config=classpath:ehcache.xml


##############################################
##             CONFIGURACION DEVTOOLS       ##
##############################################

spring.devtools.restart.enabled=false
spring.devtools.restart.additional-paths=src/main/java,src/main/resources
spring.devtools.restart.exclude=static/**,public/**
spring.devtools.livereload.enabled=true
spring.devtools.livereload.port=35729
spring.mvc.trailing-slash=false



