-- Borra tablas si existen
DROP TABLE IF EXISTS ESTUDIANTES;
DROP TABLE IF EXISTS INSTITUTOS;

-- Crear tabla INSTITUTOS
CREATE TABLE INSTITUTOS (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            codigo_instituto VARCHAR(20) NOT NULL UNIQUE,
                            nombre VARCHAR(100) NOT NULL,
                            ciudad VARCHAR(50),
                            direccion VARCHAR(100),
                            telefono VARCHAR(20),
                            email VARCHAR(100),
                            numero_profesores INT,
                            tipo VARCHAR(50),
                            anio_fundacion DATE,
                            is_deleted BOOLEAN DEFAULT FALSE,
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                            uuid UUID NOT NULL UNIQUE
);

-- Crear tabla ESTUDIANTES
CREATE TABLE ESTUDIANTES (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             nombre VARCHAR(100) NOT NULL,
                             instituto_id BIGINT NOT NULL,
                             is_deleted BOOLEAN DEFAULT FALSE,
                             created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             CONSTRAINT fk_estudiantes_institutos FOREIGN KEY (instituto_id) REFERENCES INSTITUTOS(id)
);

-- Datos de ejemplo en INSTITUTOS
INSERT INTO INSTITUTOS (codigo_instituto, nombre, anio_fundacion, ciudad, direccion, telefono, email, numero_profesores, tipo, uuid)
VALUES
    ('INST001', 'Instituto Central', '1990-01-01', 'Ciudad A', 'Calle 1', '111-11-11-11', 'central@example.com', 10, 'Público', gen_random_uuid()),
    ('INST002', 'Instituto Norte', '1985-01-01', 'Ciudad B', 'Calle 2', '222-22-22-22', 'norte@example.com', 8, 'Privado', gen_random_uuid());

-- Datos de ejemplo en ESTUDIANTES
INSERT INTO ESTUDIANTES (nombre, instituto_id) VALUES ('Juan Diaz', 1);
INSERT INTO ESTUDIANTES (nombre, instituto_id) VALUES ('Ana Lopez', 1);
INSERT INTO ESTUDIANTES (nombre, instituto_id) VALUES ('Carlos Pérez', 2);
