/*
-- Borra la tabla si existe
drop table if exists INSTITUTOS;

-- Crea la tabla INSTITUTOS
create table INSTITUTOS (
    id bigint generated by default as identity primary key,

    nombre varchar(50) not null,
    ciudad varchar(50),
    direccion varchar(100) not null,
    telefono varchar(20),
    email varchar(100),
    numero_estudiantes int,
    numero_profesores int,
    tipo varchar(50),
    anio_fundacion date,
    codigo_instituto varchar(20),

    is_deleted boolean default false,

    created_at timestamp default current_timestamp not null,
    updated_at timestamp default current_timestamp on update current_timestamp not null,

    uuid uuid not null unique
);
*/

-- Filas de ejemplo
INSERT INTO INSTITUTOS (
    nombre, ciudad, direccion, telefono, email,
    numero_estudiantes, numero_profesores, tipo,
    anio_fundacion, codigo_instituto, uuid
) VALUES (
             'Instituto Mar Mediterráneo', 'Valencia', 'Calle Olivos 23',
             '123-45-67-89', 'contacto@marval.es',
             350, 40, 'Público',
             '1987-01-01', 'INST-001', UUID()
         );

INSERT INTO INSTITUTOS (
    nombre, ciudad, direccion, telefono, email,
    numero_estudiantes, numero_profesores, tipo,
    anio_fundacion, codigo_instituto, uuid
) VALUES (
             'Colegio Sierra Blanca', 'Málaga', 'Av. Andalucía 55',
             '987-65-43-21', 'info@sierrablanca.es',
             420, 55, 'Concertado',
             '1995-09-01', 'INST-002', UUID()
         );
