/*
-- Borra la tabla si existe
drop table if exists INSTITUTOS;

-- Crea la tabla INSTITUTOS
create table INSTITUTOS (
    id bigint generated by default as identity primary key,

    nombre varchar(50) not null,
    ciudad varchar(50),
    direccion varchar(100) not null,
    telefono varchar(20),
    email varchar(100),
    numero_estudiantes int,
    numero_profesores int,
    tipo varchar(50),
    anio_fundacion date,
    codigo_instituto varchar(20),

    is_deleted boolean default false,

    created_at timestamp default current_timestamp not null,
    updated_at timestamp default current_timestamp on update current_timestamp not null,

    uuid uuid not null unique
);
*/

-- Filas de ejemplo
-- BORRAR TABLA SI EXISTE
DROP TABLE IF EXISTS INSTITUTOS;

-- CREAR TABLA INSTITUTOS
CREATE TABLE INSTITUTOS (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            codigo_instituto VARCHAR(20) NOT NULL UNIQUE,
                            nombre VARCHAR(100) NOT NULL,
                            anio_fundacion INT NOT NULL,
                            is_deleted BOOLEAN DEFAULT FALSE,
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- INSERTAR DATOS DE EJEMPLO
INSERT INTO INSTITUTOS (codigo_instituto, nombre, anio_fundacion)
VALUES ('INST001', 'Instituto Central', 1990);

INSERT INTO INSTITUTOS (codigo_instituto, nombre, anio_fundacion)
VALUES ('INST002', 'Instituto Norte', 1985);

INSERT INTO INSTITUTOS (codigo_instituto, nombre, anio_fundacion)
VALUES ('INST003', 'Instituto Sur', 2000);

INSERT INTO INSTITUTOS (codigo_instituto, nombre, anio_fundacion)
VALUES ('INST004', 'Instituto Este', 1975);

INSERT INTO INSTITUTOS (codigo_instituto, nombre, anio_fundacion)
VALUES ('INST005', 'Instituto Oeste', 2010);

DROP TABLE IF EXISTS NOMBRES;

CREATE TABLE NOMBRES (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         codigo_instituto VARCHAR(20) NOT NULL,
                         nombre VARCHAR(100) NOT NULL,
                         is_deleted BOOLEAN DEFAULT FALSE,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         CONSTRAINT fk_nombres_institutos FOREIGN KEY (codigo_instituto) REFERENCES INSTITUTOS(codigo_instituto)
);

-- Datos de ejemplo
INSERT INTO NOMBRES (codigo_instituto, nombre) VALUES ('INST001', 'Juan Diaz');
INSERT INTO NOMBRES (codigo_instituto, nombre) VALUES ('INST001', 'Ana Lopez');
INSERT INTO NOMBRES (codigo_instituto, nombre) VALUES ('INST002', 'Carlos Pérez');
INSERT INTO NOMBRES (codigo_instituto, nombre) VALUES ('INST003', 'María Gómez');
INSERT INTO NOMBRES (codigo_instituto, nombre) VALUES ('INST004', 'Luis Martínez');
