-- DROP TABLES si existen
drop table if exists NOMBRES;
drop table if exists INSTITUTOS;

-- Tabla INSTITUTOS
create table INSTITUTOS (
                            id bigint generated by default as identity PRIMARY KEY,
                            nombre varchar(50) not null unique,
                            is_deleted boolean default false,
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
                            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null
);

-- Tabla NOMBRES (códigos de instituto o nombres asociados)
create table NOMBRES (
                         id bigint generated by default as identity PRIMARY KEY,
                         codigo_instituto varchar(20) not null unique,
                         instituto_id bigint,
                         is_deleted boolean default false,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
                         updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
                         constraint fk_nombres_institutos foreign key (instituto_id) references INSTITUTOS(id)
);
