SET REFERENTIAL_INTEGRITY FALSE;

DROP TABLE IF EXISTS ESTUDIANTES;
DROP TABLE IF EXISTS INSTITUTOS;
DROP TABLE IF EXISTS NOMBRES;

SET REFERENTIAL_INTEGRITY TRUE;

CREATE TABLE INSTITUTOS (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            codigo_instituto VARCHAR(20) NOT NULL UNIQUE,
                            nombre VARCHAR(100) NOT NULL,
                            ciudad VARCHAR(50),
                            direccion VARCHAR(100),
                            telefono VARCHAR(20),
                            email VARCHAR(100),
                            numero_profesores INT NOT NULL,
                            tipo VARCHAR(50),
                            anio_fundacion DATE,
                            is_deleted BOOLEAN DEFAULT FALSE,
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                            uuid UUID NOT NULL UNIQUE
);

CREATE TABLE ESTUDIANTES (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             nombre VARCHAR(100) NOT NULL,
                             apellidos VARCHAR(100) NOT NULL,
                             dni VARCHAR(9) NOT NULL UNIQUE,
                             email VARCHAR(100),
                             fecha_nacimiento DATE,
                             instituto_id BIGINT NOT NULL,
                             is_deleted BOOLEAN DEFAULT FALSE,
                             created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             uuid UUID NOT NULL UNIQUE,
                             CONSTRAINT fk_estudiantes_institutos
                                 FOREIGN KEY (instituto_id) REFERENCES INSTITUTOS(id)
);
