-- DROP TABLES si existen (Importante: borrar la tabla hija primero)
DROP TABLE IF EXISTS ESTUDIANTES;
DROP TABLE IF EXISTS INSTITUTOS;
-- Eliminamos NOMBRES si no se usa en el modelo final
DROP TABLE IF EXISTS NOMBRES;

-- =========================================================================
-- RECREAR TABLA INSTITUTOS (ENTIDAD UNO) - Estructura Completa
-- =========================================================================
CREATE TABLE INSTITUTOS (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Campos de negocio clave
                            codigo_instituto VARCHAR(20) NOT NULL UNIQUE,
                            nombre VARCHAR(100) NOT NULL,
                            ciudad VARCHAR(50),
                            direccion VARCHAR(100),
                            telefono VARCHAR(20),
                            email VARCHAR(100),
                            numero_profesores INT,
                            tipo VARCHAR(50),
                            anio_fundacion DATE,

    -- Metadatos
                            is_deleted BOOLEAN DEFAULT FALSE,
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                            uuid UUID NOT NULL UNIQUE
);

-- =========================================================================
-- RECREAR TABLA ESTUDIANTES (ENTIDAD MUCHOS) - Estructura Completa
-- =========================================================================
CREATE TABLE ESTUDIANTES (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                             nombre VARCHAR(100) NOT NULL,
                             apellidos VARCHAR(100) NOT NULL,
                             dni VARCHAR(9) NOT NULL UNIQUE,
                             email VARCHAR(100),
                             fecha_nacimiento DATE,

                             instituto_id BIGINT NOT NULL,

                             is_deleted BOOLEAN DEFAULT FALSE,
                             created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             uuid UUID NOT NULL UNIQUE,

                             CONSTRAINT fk_estudiantes_institutos
                                 FOREIGN KEY (instituto_id) REFERENCES INSTITUTOS(id)
);
